app:
  openapi:
    url: http://localhost:3311
dlt-adapter:
  domain: http://provider-dlt-adapter:8080
blockchain:
  rpcAddress: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6
  userEthereumAddress: "0xb794f5ea0ba39494ce839613fffba74279579268"
  subscription:
    active: false
    notificationEndpoint: http://blockchain-connector-core:8080/notifications/blockchain-node
    entityTypes: >
      ProductOffering
broker:
  externalDomain: https://kong.dome-marketplace.org/scorpio
  internalDomain: http://scorpio:1026
ngsi-subscription:
  notificationEndpoint: http://provider-blockchain-connector-core:8080/notifications/orion-ld
  entityTypes: >
    ProductOffering
orion-ld-adapter:
  domain: http://provider-orionld-adapter:8080
operator:
  organization:
    id: ${ORGANIZATION_ID}
spring:
  application:
    name: Blockchain Connector Core
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: in2admin
    password: in2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migrations
  security:
    user:
      name: in2test
      password: in2pass
logging:
  level:
    ROOT: INFO
    es.in2: DEBUG
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
server:
  port: 8080

