# Spring Configuration
spring:
  application:
    name: Blockchain Connector
  main:
    web-application-type: reactive
  r2dbc:
    url:
    username: postgres
    password: postgres
    generate-unique-name: true
  flyway:
    url:
    locations: classpath:db/migrations

# Spring Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.blockchainconnector: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Application Configuration
openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    description:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:

# Operator Configuration
operator:
  organizationId:

# DLT Adapter Configuration
dlt-adapter:
  domain:

# Blockchain Configuration
blockchain:
  rpcAddress:
  userEthereumAddress:
  subscription:
    active:
    notificationEndpoint:
    eventTypes:

# Context Broker Configuration
broker:
  externalDomain:
  internalDomain:

# NGSI Subscription Configuration
ngsi-subscription:
  notificationEndpoint:
  entityTypes:

# Broker Adapter Configuration
broker-adapter:
  domain:
  paths:
    entities:
    subscriptions:
