version: "3.8"

services:

  # MySQL Service
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D83Wh$tb83D8
      MYSQL_DATABASE: mktdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
