name: Build (Test Environment)

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: build-and-deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build
        id: build
        run: ./gradlew build

      - name: Set success build status
        id: set_success_build_status
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.env.BUILD_STATUS || 'success';
            core.setOutput('build_status', status);

      - name: Set failure build status
        id: set_failure_build_status
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.env.BUILD_STATUS || 'failure';
            core.setOutput('build_status', status);
