name: "Build (Prod Environment)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Set build status and create deployment
        run: |
          echo "BUILD_STATUS=success" >> $GITHUB_ENV
          
          if [ "$BUILD_STATUS" != "success" ]; then
            if [ -n "$GITHUB_TOKEN" ] && [ -n "$GITHUB_REPOSITORY" ]; then
              DEPLOYMENT_ID=$(curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/deployments" \
                -d '{"ref": "'"$GITHUB_SHA"'", "environment": "test", "auto_merge": false}' | jq -r '.id')
          
              curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$DEPLOYMENT_ID/statuses" \
                -d '{"state": "failure"}'
            else
              echo "Error: GITHUB_TOKEN or GITHUB_REPOSITORY is not set."
            fi
          fi
