name: "Build (Prod Environment)"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Set build status
        id: set_build_status
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.env.BUILD_STATUS;
            core.setOutput('build_status', status);

            if (status !== 'success') {
              const { data } = await github.repos.createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: process.env.GITHUB_SHA,
                environment: 'test',
                auto_merge: false,
              });
            
              await github.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: data.id,
                state: 'failure',
              });
            }
